// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assignment_detail_with_client`, `assignment_submit_with_client`, `assignment_upload_with_client`, `assignments_for_course_with_client`, `assignments_undone_with_client`, `auth_finish_with_client`, `auth_start_with_client`, `course_download_targets`, `courses_with_client`, `create_download_task`, `decode_session_payload`, `download_course_targets`, `download_resource_to_path`, `download_tasks_map`, `download_tasks`, `encode_session_payload`, `error`, `fetch_course_resource_details`, `finish_download_task`, `fs_error`, `is_terminal_download_state`, `lock_recover`, `next_download_path_reserved`, `next_download_path`, `read_download_status`, `refreshed_session`, `resource_detail_with_client`, `resource_download_course_task`, `resource_download_task`, `resources_for_course_with_client`, `sanitize_file_name`, `shared_default_client`, `to_ffi_error`, `update_download_status`, `validate_upload_file_metadata`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DownloadTask`, `ResourceDownloadTaskRequest`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

Future<FfiAuthStartResponse> authStart({required String username}) =>
    RustLib.instance.api.crateApiAuthStart(username: username);

Future<FfiAuthFinishResponse> authFinish(
        {required FfiAuthFinishRequest request, required FfiLoginFlow flow}) =>
    RustLib.instance.api.crateApiAuthFinish(request: request, flow: flow);

Future<FfiAuthSessionResponse> sessionSummary(
        {required String sessionPayload}) =>
    RustLib.instance.api.crateApiSessionSummary(sessionPayload: sessionPayload);

Future<FfiClientCapabilities> capabilities() =>
    RustLib.instance.api.crateApiCapabilities();

Future<FfiAttendanceQrPayload> parseAttendanceQrPayloadText(
        {required String payload}) =>
    RustLib.instance.api.crateApiParseAttendanceQrPayloadText(payload: payload);

Future<FfiCourseResponse> courses(
        {required String sessionPayload, required bool withGoing}) =>
    RustLib.instance.api
        .crateApiCourses(sessionPayload: sessionPayload, withGoing: withGoing);

Future<FfiAssignmentListResponse> assignmentsUndone(
        {required String sessionPayload}) =>
    RustLib.instance.api
        .crateApiAssignmentsUndone(sessionPayload: sessionPayload);

Future<FfiAssignmentListResponse> assignmentsForCourse(
        {required String sessionPayload,
        required String siteId,
        required String siteName,
        required String keyword}) =>
    RustLib.instance.api.crateApiAssignmentsForCourse(
        sessionPayload: sessionPayload,
        siteId: siteId,
        siteName: siteName,
        keyword: keyword);

Future<FfiAssignmentDetailResponse> assignmentDetail(
        {required String sessionPayload, required String assignmentId}) =>
    RustLib.instance.api.crateApiAssignmentDetail(
        sessionPayload: sessionPayload, assignmentId: assignmentId);

Future<FfiAssignmentUploadResponse> assignmentUpload(
        {required String sessionPayload,
        required String assignmentId,
        required String filePath}) =>
    RustLib.instance.api.crateApiAssignmentUpload(
        sessionPayload: sessionPayload,
        assignmentId: assignmentId,
        filePath: filePath);

Future<FfiAssignmentSubmitResponse> assignmentSubmit(
        {required String sessionPayload,
        required String assignmentId,
        required String content,
        required List<String> attachmentIds}) =>
    RustLib.instance.api.crateApiAssignmentSubmit(
        sessionPayload: sessionPayload,
        assignmentId: assignmentId,
        content: content,
        attachmentIds: attachmentIds);

Future<FfiCourseResourcesResponse> resourcesForCourse(
        {required String sessionPayload,
        required String siteId,
        required String siteName}) =>
    RustLib.instance.api.crateApiResourcesForCourse(
        sessionPayload: sessionPayload, siteId: siteId, siteName: siteName);

Future<FfiCourseResourceDetailResponse> resourceDetail(
        {required String sessionPayload,
        required String resourceId,
        required String siteId,
        required String siteName}) =>
    RustLib.instance.api.crateApiResourceDetail(
        sessionPayload: sessionPayload,
        resourceId: resourceId,
        siteId: siteId,
        siteName: siteName);

Future<FfiDownloadTaskStartResponse> resourceDownloadStart(
        {required String sessionPayload,
        required String resourceId,
        required String siteId,
        required String siteName,
        required String outputPath}) =>
    RustLib.instance.api.crateApiResourceDownloadStart(
        sessionPayload: sessionPayload,
        resourceId: resourceId,
        siteId: siteId,
        siteName: siteName,
        outputPath: outputPath);

Future<FfiDownloadTaskStartResponse> resourceDownloadCourseStart(
        {required String sessionPayload,
        required String siteId,
        required String siteName,
        required String outputDir}) =>
    RustLib.instance.api.crateApiResourceDownloadCourseStart(
        sessionPayload: sessionPayload,
        siteId: siteId,
        siteName: siteName,
        outputDir: outputDir);

Future<FfiDownloadTaskStatus> downloadTaskStatus({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadTaskStatus(taskId: taskId);

Future<FfiDownloadTaskStatus> downloadTaskCancel({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadTaskCancel(taskId: taskId);

Future<void> downloadTaskDispose({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadTaskDispose(taskId: taskId);

Future<FfiLogoutResponse> logout() => RustLib.instance.api.crateApiLogout();

class FfiAssignmentDetailResponse {
  final String className;
  final String comment;
  final String content;
  final String endTime;
  final String id;
  final bool isOvertimeCommit;
  final double? score;
  final String siteId;
  final String siteName;
  final String startTime;
  final FfiAssignmentStatus status;
  final String submittedAt;
  final List<FfiAssignmentResource> submittedAttachments;
  final String submittedContent;
  final List<FfiAssignmentResource> teacherResources;
  final String title;
  final String? updatedSessionPayload;

  const FfiAssignmentDetailResponse({
    required this.className,
    required this.comment,
    required this.content,
    required this.endTime,
    required this.id,
    required this.isOvertimeCommit,
    this.score,
    required this.siteId,
    required this.siteName,
    required this.startTime,
    required this.status,
    required this.submittedAt,
    required this.submittedAttachments,
    required this.submittedContent,
    required this.teacherResources,
    required this.title,
    this.updatedSessionPayload,
  });

  @override
  int get hashCode =>
      className.hashCode ^
      comment.hashCode ^
      content.hashCode ^
      endTime.hashCode ^
      id.hashCode ^
      isOvertimeCommit.hashCode ^
      score.hashCode ^
      siteId.hashCode ^
      siteName.hashCode ^
      startTime.hashCode ^
      status.hashCode ^
      submittedAt.hashCode ^
      submittedAttachments.hashCode ^
      submittedContent.hashCode ^
      teacherResources.hashCode ^
      title.hashCode ^
      updatedSessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAssignmentDetailResponse &&
          runtimeType == other.runtimeType &&
          className == other.className &&
          comment == other.comment &&
          content == other.content &&
          endTime == other.endTime &&
          id == other.id &&
          isOvertimeCommit == other.isOvertimeCommit &&
          score == other.score &&
          siteId == other.siteId &&
          siteName == other.siteName &&
          startTime == other.startTime &&
          status == other.status &&
          submittedAt == other.submittedAt &&
          submittedAttachments == other.submittedAttachments &&
          submittedContent == other.submittedContent &&
          teacherResources == other.teacherResources &&
          title == other.title &&
          updatedSessionPayload == other.updatedSessionPayload;
}

class FfiAssignmentListResponse {
  final List<FfiAssignmentSummary> records;
  final String? updatedSessionPayload;

  const FfiAssignmentListResponse({
    required this.records,
    this.updatedSessionPayload,
  });

  @override
  int get hashCode => records.hashCode ^ updatedSessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAssignmentListResponse &&
          runtimeType == other.runtimeType &&
          records == other.records &&
          updatedSessionPayload == other.updatedSessionPayload;
}

class FfiAssignmentResource {
  final String? ext;
  final String name;
  final String? previewUrl;
  final String resourceId;
  final String? storageId;

  const FfiAssignmentResource({
    this.ext,
    required this.name,
    this.previewUrl,
    required this.resourceId,
    this.storageId,
  });

  @override
  int get hashCode =>
      ext.hashCode ^
      name.hashCode ^
      previewUrl.hashCode ^
      resourceId.hashCode ^
      storageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAssignmentResource &&
          runtimeType == other.runtimeType &&
          ext == other.ext &&
          name == other.name &&
          previewUrl == other.previewUrl &&
          resourceId == other.resourceId &&
          storageId == other.storageId;
}

enum FfiAssignmentStatus {
  pending,
  submitted,
  expired,
  ;
}

class FfiAssignmentSubmitResponse {
  final bool ok;
  final String? updatedSessionPayload;

  const FfiAssignmentSubmitResponse({
    required this.ok,
    this.updatedSessionPayload,
  });

  @override
  int get hashCode => ok.hashCode ^ updatedSessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAssignmentSubmitResponse &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          updatedSessionPayload == other.updatedSessionPayload;
}

class FfiAssignmentSummary {
  final String endTime;
  final String id;
  final String siteId;
  final String siteName;
  final String source;
  final String startTime;
  final FfiAssignmentStatus status;
  final String title;

  const FfiAssignmentSummary({
    required this.endTime,
    required this.id,
    required this.siteId,
    required this.siteName,
    required this.source,
    required this.startTime,
    required this.status,
    required this.title,
  });

  @override
  int get hashCode =>
      endTime.hashCode ^
      id.hashCode ^
      siteId.hashCode ^
      siteName.hashCode ^
      source.hashCode ^
      startTime.hashCode ^
      status.hashCode ^
      title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAssignmentSummary &&
          runtimeType == other.runtimeType &&
          endTime == other.endTime &&
          id == other.id &&
          siteId == other.siteId &&
          siteName == other.siteName &&
          source == other.source &&
          startTime == other.startTime &&
          status == other.status &&
          title == other.title;
}

class FfiAssignmentUploadResponse {
  final String assignmentId;
  final String fileName;
  final String? previewUrl;
  final String resourceId;
  final String siteId;
  final String siteName;
  final String? updatedSessionPayload;

  const FfiAssignmentUploadResponse({
    required this.assignmentId,
    required this.fileName,
    this.previewUrl,
    required this.resourceId,
    required this.siteId,
    required this.siteName,
    this.updatedSessionPayload,
  });

  @override
  int get hashCode =>
      assignmentId.hashCode ^
      fileName.hashCode ^
      previewUrl.hashCode ^
      resourceId.hashCode ^
      siteId.hashCode ^
      siteName.hashCode ^
      updatedSessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAssignmentUploadResponse &&
          runtimeType == other.runtimeType &&
          assignmentId == other.assignmentId &&
          fileName == other.fileName &&
          previewUrl == other.previewUrl &&
          resourceId == other.resourceId &&
          siteId == other.siteId &&
          siteName == other.siteName &&
          updatedSessionPayload == other.updatedSessionPayload;
}

class FfiAttendanceQrPayload {
  final String attendanceId;
  final String siteId;
  final String createTime;
  final String classLessonId;

  const FfiAttendanceQrPayload({
    required this.attendanceId,
    required this.siteId,
    required this.createTime,
    required this.classLessonId,
  });

  @override
  int get hashCode =>
      attendanceId.hashCode ^
      siteId.hashCode ^
      createTime.hashCode ^
      classLessonId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAttendanceQrPayload &&
          runtimeType == other.runtimeType &&
          attendanceId == other.attendanceId &&
          siteId == other.siteId &&
          createTime == other.createTime &&
          classLessonId == other.classLessonId;
}

class FfiAuthError implements FrbException {
  final FfiAuthErrorCode code;
  final String message;
  final BigInt? retryAfterSeconds;

  const FfiAuthError({
    required this.code,
    required this.message,
    this.retryAfterSeconds,
  });

  @override
  int get hashCode =>
      code.hashCode ^ message.hashCode ^ retryAfterSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          retryAfterSeconds == other.retryAfterSeconds;
}

enum FfiAuthErrorCode {
  captchaRequired,
  captchaInvalid,
  emptyUpload,
  fileTooLarge,
  invalidFileName,
  fileTypeNotAllowed,
  flowExpired,
  invalidCredentials,
  roleNotFound,
  secureStorageUnavailable,
  sessionExpired,
  upstreamUnavailable,
  unknownAuthError,
  cancelled,
  invalidInput,
  notFound,
  fileSystem,
  rateLimited,
  ;
}

class FfiAuthFinishRequest {
  final String? captcha;
  final String flowId;
  final String password;
  final FfiRoleName? role;
  final String username;

  const FfiAuthFinishRequest({
    this.captcha,
    required this.flowId,
    required this.password,
    this.role,
    required this.username,
  });

  @override
  int get hashCode =>
      captcha.hashCode ^
      flowId.hashCode ^
      password.hashCode ^
      role.hashCode ^
      username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthFinishRequest &&
          runtimeType == other.runtimeType &&
          captcha == other.captcha &&
          flowId == other.flowId &&
          password == other.password &&
          role == other.role &&
          username == other.username;
}

class FfiAuthFinishResponse {
  final FfiAuthFinishResult auth;
  final String sessionPayload;

  const FfiAuthFinishResponse({
    required this.auth,
    required this.sessionPayload,
  });

  @override
  int get hashCode => auth.hashCode ^ sessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthFinishResponse &&
          runtimeType == other.runtimeType &&
          auth == other.auth &&
          sessionPayload == other.sessionPayload;
}

class FfiAuthFinishResult {
  final List<FfiRoleInfo> roles;
  final FfiRoleName selectedRole;
  final FfiSessionUser user;

  const FfiAuthFinishResult({
    required this.roles,
    required this.selectedRole,
    required this.user,
  });

  @override
  int get hashCode => roles.hashCode ^ selectedRole.hashCode ^ user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthFinishResult &&
          runtimeType == other.runtimeType &&
          roles == other.roles &&
          selectedRole == other.selectedRole &&
          user == other.user;
}

class FfiAuthSessionResponse {
  final FfiRoleName selectedRole;
  final FfiSessionUser user;

  const FfiAuthSessionResponse({
    required this.selectedRole,
    required this.user,
  });

  @override
  int get hashCode => selectedRole.hashCode ^ user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthSessionResponse &&
          runtimeType == other.runtimeType &&
          selectedRole == other.selectedRole &&
          user == other.user;
}

class FfiAuthStartResponse {
  final FfiAuthStartResult auth;
  final FfiLoginFlow flow;

  const FfiAuthStartResponse({
    required this.auth,
    required this.flow,
  });

  @override
  int get hashCode => auth.hashCode ^ flow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthStartResponse &&
          runtimeType == other.runtimeType &&
          auth == other.auth &&
          flow == other.flow;
}

class FfiAuthStartResult {
  final String? captchaImage;
  final String flowId;
  final bool requiresCaptcha;

  const FfiAuthStartResult({
    this.captchaImage,
    required this.flowId,
    required this.requiresCaptcha,
  });

  @override
  int get hashCode =>
      captchaImage.hashCode ^ flowId.hashCode ^ requiresCaptcha.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthStartResult &&
          runtimeType == other.runtimeType &&
          captchaImage == other.captchaImage &&
          flowId == other.flowId &&
          requiresCaptcha == other.requiresCaptcha;
}

class FfiClientCapabilities {
  final bool selfAttendance;
  final bool attendanceQrPayloadParsing;

  const FfiClientCapabilities({
    required this.selfAttendance,
    required this.attendanceQrPayloadParsing,
  });

  @override
  int get hashCode =>
      selfAttendance.hashCode ^ attendanceQrPayloadParsing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiClientCapabilities &&
          runtimeType == other.runtimeType &&
          selfAttendance == other.selfAttendance &&
          attendanceQrPayloadParsing == other.attendanceQrPayloadParsing;
}

class FfiCourseResourceDetail {
  final String? description;
  final String? downloadUrl;
  final String? ext;
  final String name;
  final String resourceId;
  final String siteId;
  final String siteName;
  final BigInt? sizeBytes;
  final String updatedAt;

  const FfiCourseResourceDetail({
    this.description,
    this.downloadUrl,
    this.ext,
    required this.name,
    required this.resourceId,
    required this.siteId,
    required this.siteName,
    this.sizeBytes,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      description.hashCode ^
      downloadUrl.hashCode ^
      ext.hashCode ^
      name.hashCode ^
      resourceId.hashCode ^
      siteId.hashCode ^
      siteName.hashCode ^
      sizeBytes.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCourseResourceDetail &&
          runtimeType == other.runtimeType &&
          description == other.description &&
          downloadUrl == other.downloadUrl &&
          ext == other.ext &&
          name == other.name &&
          resourceId == other.resourceId &&
          siteId == other.siteId &&
          siteName == other.siteName &&
          sizeBytes == other.sizeBytes &&
          updatedAt == other.updatedAt;
}

class FfiCourseResourceDetailResponse {
  final FfiCourseResourceDetail detail;
  final String? updatedSessionPayload;

  const FfiCourseResourceDetailResponse({
    required this.detail,
    this.updatedSessionPayload,
  });

  @override
  int get hashCode => detail.hashCode ^ updatedSessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCourseResourceDetailResponse &&
          runtimeType == other.runtimeType &&
          detail == other.detail &&
          updatedSessionPayload == other.updatedSessionPayload;
}

class FfiCourseResourceSummary {
  final String? ext;
  final String name;
  final String resourceId;
  final String siteId;
  final String siteName;
  final BigInt? sizeBytes;
  final String updatedAt;

  const FfiCourseResourceSummary({
    this.ext,
    required this.name,
    required this.resourceId,
    required this.siteId,
    required this.siteName,
    this.sizeBytes,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      ext.hashCode ^
      name.hashCode ^
      resourceId.hashCode ^
      siteId.hashCode ^
      siteName.hashCode ^
      sizeBytes.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCourseResourceSummary &&
          runtimeType == other.runtimeType &&
          ext == other.ext &&
          name == other.name &&
          resourceId == other.resourceId &&
          siteId == other.siteId &&
          siteName == other.siteName &&
          sizeBytes == other.sizeBytes &&
          updatedAt == other.updatedAt;
}

class FfiCourseResourcesResponse {
  final List<FfiCourseResourceSummary> records;
  final String? updatedSessionPayload;

  const FfiCourseResourcesResponse({
    required this.records,
    this.updatedSessionPayload,
  });

  @override
  int get hashCode => records.hashCode ^ updatedSessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCourseResourcesResponse &&
          runtimeType == other.runtimeType &&
          records == other.records &&
          updatedSessionPayload == other.updatedSessionPayload;
}

class FfiCourseResponse {
  final List<FfiCourseSite> records;
  final List<FfiGoingSite> goingSites;
  final String? updatedSessionPayload;

  const FfiCourseResponse({
    required this.records,
    required this.goingSites,
    this.updatedSessionPayload,
  });

  @override
  int get hashCode =>
      records.hashCode ^ goingSites.hashCode ^ updatedSessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCourseResponse &&
          runtimeType == other.runtimeType &&
          records == other.records &&
          goingSites == other.goingSites &&
          updatedSessionPayload == other.updatedSessionPayload;
}

class FfiCourseSite {
  final String id;
  final String siteName;

  const FfiCourseSite({
    required this.id,
    required this.siteName,
  });

  @override
  int get hashCode => id.hashCode ^ siteName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCourseSite &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          siteName == other.siteName;
}

class FfiDownloadTaskStartResponse {
  final String taskId;
  final FfiDownloadTaskStatus status;

  const FfiDownloadTaskStartResponse({
    required this.taskId,
    required this.status,
  });

  @override
  int get hashCode => taskId.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiDownloadTaskStartResponse &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          status == other.status;
}

enum FfiDownloadTaskState {
  queued,
  running,
  succeeded,
  failed,
  cancelled,
  ;
}

class FfiDownloadTaskStatus {
  final String taskId;
  final FfiDownloadTaskState state;
  final int current;
  final int total;
  final BigInt bytesDownloaded;
  final String? currentFileName;
  final List<String> writtenPaths;
  final List<FfiCourseResourceDetail> records;
  final String? errorMessage;
  final String? updatedSessionPayload;

  const FfiDownloadTaskStatus({
    required this.taskId,
    required this.state,
    required this.current,
    required this.total,
    required this.bytesDownloaded,
    this.currentFileName,
    required this.writtenPaths,
    required this.records,
    this.errorMessage,
    this.updatedSessionPayload,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^
      state.hashCode ^
      current.hashCode ^
      total.hashCode ^
      bytesDownloaded.hashCode ^
      currentFileName.hashCode ^
      writtenPaths.hashCode ^
      records.hashCode ^
      errorMessage.hashCode ^
      updatedSessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiDownloadTaskStatus &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          state == other.state &&
          current == other.current &&
          total == other.total &&
          bytesDownloaded == other.bytesDownloaded &&
          currentFileName == other.currentFileName &&
          writtenPaths == other.writtenPaths &&
          records == other.records &&
          errorMessage == other.errorMessage &&
          updatedSessionPayload == other.updatedSessionPayload;
}

class FfiGoingSite {
  final String groupId;
  final String siteId;

  const FfiGoingSite({
    required this.groupId,
    required this.siteId,
  });

  @override
  int get hashCode => groupId.hashCode ^ siteId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiGoingSite &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          siteId == other.siteId;
}

class FfiLoginFlow {
  final String? captchaId;
  final String? captchaImage;
  final String cookie;
  final String execution;
  final String username;

  const FfiLoginFlow({
    this.captchaId,
    this.captchaImage,
    required this.cookie,
    required this.execution,
    required this.username,
  });

  @override
  int get hashCode =>
      captchaId.hashCode ^
      captchaImage.hashCode ^
      cookie.hashCode ^
      execution.hashCode ^
      username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiLoginFlow &&
          runtimeType == other.runtimeType &&
          captchaId == other.captchaId &&
          captchaImage == other.captchaImage &&
          cookie == other.cookie &&
          execution == other.execution &&
          username == other.username;
}

class FfiLogoutResponse {
  final bool clearSession;

  const FfiLogoutResponse({
    required this.clearSession,
  });

  @override
  int get hashCode => clearSession.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiLogoutResponse &&
          runtimeType == other.runtimeType &&
          clearSession == other.clearSession;
}

class FfiRoleInfo {
  final String domainId;
  final String domainName;
  final String id;
  final String roleAlias;
  final String roleId;
  final FfiRoleName roleName;

  const FfiRoleInfo({
    required this.domainId,
    required this.domainName,
    required this.id,
    required this.roleAlias,
    required this.roleId,
    required this.roleName,
  });

  @override
  int get hashCode =>
      domainId.hashCode ^
      domainName.hashCode ^
      id.hashCode ^
      roleAlias.hashCode ^
      roleId.hashCode ^
      roleName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiRoleInfo &&
          runtimeType == other.runtimeType &&
          domainId == other.domainId &&
          domainName == other.domainName &&
          id == other.id &&
          roleAlias == other.roleAlias &&
          roleId == other.roleId &&
          roleName == other.roleName;
}

enum FfiRoleName {
  student,
  teacher,
  assistant,
  ;
}

class FfiSessionUser {
  final String account;
  final String realName;
  final String userId;
  final String userName;

  const FfiSessionUser({
    required this.account,
    required this.realName,
    required this.userId,
    required this.userName,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      realName.hashCode ^
      userId.hashCode ^
      userName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiSessionUser &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          realName == other.realName &&
          userId == other.userId &&
          userName == other.userName;
}
