// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `auth_finish_with_client`, `auth_start_with_client`, `courses_with_client`, `decode_session_payload`, `default_client`, `encode_session_payload`, `error`, `now_ms`, `to_ffi_error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

Future<FfiAuthStartResponse> authStart({required String username}) =>
    RustLib.instance.api.crateApiAuthStart(username: username);

Future<FfiAuthFinishResponse> authFinish({
  required FfiAuthFinishRequest request,
  required FfiLoginFlow flow,
}) => RustLib.instance.api.crateApiAuthFinish(request: request, flow: flow);

Future<FfiAuthSessionResponse> sessionSummary({
  required String sessionPayload,
}) =>
    RustLib.instance.api.crateApiSessionSummary(sessionPayload: sessionPayload);

Future<FfiCourseResponse> courses({
  required String sessionPayload,
  required bool withGoing,
}) => RustLib.instance.api.crateApiCourses(
  sessionPayload: sessionPayload,
  withGoing: withGoing,
);

Future<FfiLogoutResponse> logout() => RustLib.instance.api.crateApiLogout();

class FfiAuthError implements FrbException {
  final FfiAuthErrorCode code;
  final String message;
  final BigInt? retryAfterSeconds;

  const FfiAuthError({
    required this.code,
    required this.message,
    this.retryAfterSeconds,
  });

  @override
  int get hashCode =>
      code.hashCode ^ message.hashCode ^ retryAfterSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          retryAfterSeconds == other.retryAfterSeconds;
}

enum FfiAuthErrorCode {
  captchaRequired,
  captchaInvalid,
  emptyUpload,
  fileTooLarge,
  invalidFileName,
  fileTypeNotAllowed,
  flowExpired,
  invalidCredentials,
  roleNotFound,
  secureStorageUnavailable,
  sessionExpired,
  upstreamUnavailable,
  unknownAuthError,
}

class FfiAuthFinishRequest {
  final String? captcha;
  final String flowId;
  final String password;
  final FfiRoleName? role;
  final String username;

  const FfiAuthFinishRequest({
    this.captcha,
    required this.flowId,
    required this.password,
    this.role,
    required this.username,
  });

  @override
  int get hashCode =>
      captcha.hashCode ^
      flowId.hashCode ^
      password.hashCode ^
      role.hashCode ^
      username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthFinishRequest &&
          runtimeType == other.runtimeType &&
          captcha == other.captcha &&
          flowId == other.flowId &&
          password == other.password &&
          role == other.role &&
          username == other.username;
}

class FfiAuthFinishResponse {
  final FfiAuthFinishResult auth;
  final String sessionPayload;

  const FfiAuthFinishResponse({
    required this.auth,
    required this.sessionPayload,
  });

  @override
  int get hashCode => auth.hashCode ^ sessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthFinishResponse &&
          runtimeType == other.runtimeType &&
          auth == other.auth &&
          sessionPayload == other.sessionPayload;
}

class FfiAuthFinishResult {
  final List<FfiRoleInfo> roles;
  final FfiRoleName selectedRole;
  final FfiSessionUser user;

  const FfiAuthFinishResult({
    required this.roles,
    required this.selectedRole,
    required this.user,
  });

  @override
  int get hashCode => roles.hashCode ^ selectedRole.hashCode ^ user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthFinishResult &&
          runtimeType == other.runtimeType &&
          roles == other.roles &&
          selectedRole == other.selectedRole &&
          user == other.user;
}

class FfiAuthSessionResponse {
  final FfiRoleName selectedRole;
  final FfiSessionUser user;

  const FfiAuthSessionResponse({
    required this.selectedRole,
    required this.user,
  });

  @override
  int get hashCode => selectedRole.hashCode ^ user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthSessionResponse &&
          runtimeType == other.runtimeType &&
          selectedRole == other.selectedRole &&
          user == other.user;
}

class FfiAuthStartResponse {
  final FfiAuthStartResult auth;
  final FfiLoginFlow flow;

  const FfiAuthStartResponse({required this.auth, required this.flow});

  @override
  int get hashCode => auth.hashCode ^ flow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthStartResponse &&
          runtimeType == other.runtimeType &&
          auth == other.auth &&
          flow == other.flow;
}

class FfiAuthStartResult {
  final String? captchaImage;
  final String flowId;
  final bool requiresCaptcha;

  const FfiAuthStartResult({
    this.captchaImage,
    required this.flowId,
    required this.requiresCaptcha,
  });

  @override
  int get hashCode =>
      captchaImage.hashCode ^ flowId.hashCode ^ requiresCaptcha.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthStartResult &&
          runtimeType == other.runtimeType &&
          captchaImage == other.captchaImage &&
          flowId == other.flowId &&
          requiresCaptcha == other.requiresCaptcha;
}

class FfiCourseResponse {
  final List<FfiCourseSite> records;
  final List<FfiGoingSite> goingSites;
  final String? updatedSessionPayload;

  const FfiCourseResponse({
    required this.records,
    required this.goingSites,
    this.updatedSessionPayload,
  });

  @override
  int get hashCode =>
      records.hashCode ^ goingSites.hashCode ^ updatedSessionPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCourseResponse &&
          runtimeType == other.runtimeType &&
          records == other.records &&
          goingSites == other.goingSites &&
          updatedSessionPayload == other.updatedSessionPayload;
}

class FfiCourseSite {
  final String id;
  final String siteName;

  const FfiCourseSite({required this.id, required this.siteName});

  @override
  int get hashCode => id.hashCode ^ siteName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCourseSite &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          siteName == other.siteName;
}

class FfiGoingSite {
  final String groupId;
  final String siteId;

  const FfiGoingSite({required this.groupId, required this.siteId});

  @override
  int get hashCode => groupId.hashCode ^ siteId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiGoingSite &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          siteId == other.siteId;
}

class FfiLoginFlow {
  final String? captchaId;
  final String? captchaImage;
  final String cookie;
  final BigInt createdAtMs;
  final String execution;
  final String username;

  const FfiLoginFlow({
    this.captchaId,
    this.captchaImage,
    required this.cookie,
    required this.createdAtMs,
    required this.execution,
    required this.username,
  });

  @override
  int get hashCode =>
      captchaId.hashCode ^
      captchaImage.hashCode ^
      cookie.hashCode ^
      createdAtMs.hashCode ^
      execution.hashCode ^
      username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiLoginFlow &&
          runtimeType == other.runtimeType &&
          captchaId == other.captchaId &&
          captchaImage == other.captchaImage &&
          cookie == other.cookie &&
          createdAtMs == other.createdAtMs &&
          execution == other.execution &&
          username == other.username;
}

class FfiLogoutResponse {
  final bool clearSession;

  const FfiLogoutResponse({required this.clearSession});

  @override
  int get hashCode => clearSession.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiLogoutResponse &&
          runtimeType == other.runtimeType &&
          clearSession == other.clearSession;
}

class FfiRoleInfo {
  final String domainId;
  final String domainName;
  final String id;
  final String roleAliase;
  final String roleId;
  final FfiRoleName roleName;

  const FfiRoleInfo({
    required this.domainId,
    required this.domainName,
    required this.id,
    required this.roleAliase,
    required this.roleId,
    required this.roleName,
  });

  @override
  int get hashCode =>
      domainId.hashCode ^
      domainName.hashCode ^
      id.hashCode ^
      roleAliase.hashCode ^
      roleId.hashCode ^
      roleName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiRoleInfo &&
          runtimeType == other.runtimeType &&
          domainId == other.domainId &&
          domainName == other.domainName &&
          id == other.id &&
          roleAliase == other.roleAliase &&
          roleId == other.roleId &&
          roleName == other.roleName;
}

enum FfiRoleName { student, teacher, assistant }

class FfiSessionUser {
  final String account;
  final String realName;
  final String userId;
  final String userName;

  const FfiSessionUser({
    required this.account,
    required this.realName,
    required this.userId,
    required this.userName,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      realName.hashCode ^
      userId.hashCode ^
      userName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiSessionUser &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          realName == other.realName &&
          userId == other.userId &&
          userName == other.userName;
}
