// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FfiAuthFinishRequest dco_decode_box_autoadd_ffi_auth_finish_request(
      dynamic raw);

  @protected
  FfiLoginFlow dco_decode_box_autoadd_ffi_login_flow(dynamic raw);

  @protected
  FfiRoleName dco_decode_box_autoadd_ffi_role_name(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FfiAssignmentDetailResponse dco_decode_ffi_assignment_detail_response(
      dynamic raw);

  @protected
  FfiAssignmentListResponse dco_decode_ffi_assignment_list_response(
      dynamic raw);

  @protected
  FfiAssignmentResource dco_decode_ffi_assignment_resource(dynamic raw);

  @protected
  FfiAssignmentStatus dco_decode_ffi_assignment_status(dynamic raw);

  @protected
  FfiAssignmentSubmitResponse dco_decode_ffi_assignment_submit_response(
      dynamic raw);

  @protected
  FfiAssignmentSummary dco_decode_ffi_assignment_summary(dynamic raw);

  @protected
  FfiAssignmentUploadResponse dco_decode_ffi_assignment_upload_response(
      dynamic raw);

  @protected
  FfiAttendanceQrPayload dco_decode_ffi_attendance_qr_payload(dynamic raw);

  @protected
  FfiAuthError dco_decode_ffi_auth_error(dynamic raw);

  @protected
  FfiAuthErrorCode dco_decode_ffi_auth_error_code(dynamic raw);

  @protected
  FfiAuthFinishRequest dco_decode_ffi_auth_finish_request(dynamic raw);

  @protected
  FfiAuthFinishResponse dco_decode_ffi_auth_finish_response(dynamic raw);

  @protected
  FfiAuthFinishResult dco_decode_ffi_auth_finish_result(dynamic raw);

  @protected
  FfiAuthSessionResponse dco_decode_ffi_auth_session_response(dynamic raw);

  @protected
  FfiAuthStartResponse dco_decode_ffi_auth_start_response(dynamic raw);

  @protected
  FfiAuthStartResult dco_decode_ffi_auth_start_result(dynamic raw);

  @protected
  FfiClientCapabilities dco_decode_ffi_client_capabilities(dynamic raw);

  @protected
  FfiCourseResourceDetail dco_decode_ffi_course_resource_detail(dynamic raw);

  @protected
  FfiCourseResourceDetailResponse
      dco_decode_ffi_course_resource_detail_response(dynamic raw);

  @protected
  FfiCourseResourceSummary dco_decode_ffi_course_resource_summary(dynamic raw);

  @protected
  FfiCourseResourcesResponse dco_decode_ffi_course_resources_response(
      dynamic raw);

  @protected
  FfiCourseResponse dco_decode_ffi_course_response(dynamic raw);

  @protected
  FfiCourseSite dco_decode_ffi_course_site(dynamic raw);

  @protected
  FfiDownloadTaskStartResponse dco_decode_ffi_download_task_start_response(
      dynamic raw);

  @protected
  FfiDownloadTaskState dco_decode_ffi_download_task_state(dynamic raw);

  @protected
  FfiDownloadTaskStatus dco_decode_ffi_download_task_status(dynamic raw);

  @protected
  FfiGoingSite dco_decode_ffi_going_site(dynamic raw);

  @protected
  FfiLoginFlow dco_decode_ffi_login_flow(dynamic raw);

  @protected
  FfiLogoutResponse dco_decode_ffi_logout_response(dynamic raw);

  @protected
  FfiRoleInfo dco_decode_ffi_role_info(dynamic raw);

  @protected
  FfiRoleName dco_decode_ffi_role_name(dynamic raw);

  @protected
  FfiSessionUser dco_decode_ffi_session_user(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FfiAssignmentResource> dco_decode_list_ffi_assignment_resource(
      dynamic raw);

  @protected
  List<FfiAssignmentSummary> dco_decode_list_ffi_assignment_summary(
      dynamic raw);

  @protected
  List<FfiCourseResourceDetail> dco_decode_list_ffi_course_resource_detail(
      dynamic raw);

  @protected
  List<FfiCourseResourceSummary> dco_decode_list_ffi_course_resource_summary(
      dynamic raw);

  @protected
  List<FfiCourseSite> dco_decode_list_ffi_course_site(dynamic raw);

  @protected
  List<FfiGoingSite> dco_decode_list_ffi_going_site(dynamic raw);

  @protected
  List<FfiRoleInfo> dco_decode_list_ffi_role_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  FfiRoleName? dco_decode_opt_box_autoadd_ffi_role_name(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FfiAuthFinishRequest sse_decode_box_autoadd_ffi_auth_finish_request(
      SseDeserializer deserializer);

  @protected
  FfiLoginFlow sse_decode_box_autoadd_ffi_login_flow(
      SseDeserializer deserializer);

  @protected
  FfiRoleName sse_decode_box_autoadd_ffi_role_name(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FfiAssignmentDetailResponse sse_decode_ffi_assignment_detail_response(
      SseDeserializer deserializer);

  @protected
  FfiAssignmentListResponse sse_decode_ffi_assignment_list_response(
      SseDeserializer deserializer);

  @protected
  FfiAssignmentResource sse_decode_ffi_assignment_resource(
      SseDeserializer deserializer);

  @protected
  FfiAssignmentStatus sse_decode_ffi_assignment_status(
      SseDeserializer deserializer);

  @protected
  FfiAssignmentSubmitResponse sse_decode_ffi_assignment_submit_response(
      SseDeserializer deserializer);

  @protected
  FfiAssignmentSummary sse_decode_ffi_assignment_summary(
      SseDeserializer deserializer);

  @protected
  FfiAssignmentUploadResponse sse_decode_ffi_assignment_upload_response(
      SseDeserializer deserializer);

  @protected
  FfiAttendanceQrPayload sse_decode_ffi_attendance_qr_payload(
      SseDeserializer deserializer);

  @protected
  FfiAuthError sse_decode_ffi_auth_error(SseDeserializer deserializer);

  @protected
  FfiAuthErrorCode sse_decode_ffi_auth_error_code(SseDeserializer deserializer);

  @protected
  FfiAuthFinishRequest sse_decode_ffi_auth_finish_request(
      SseDeserializer deserializer);

  @protected
  FfiAuthFinishResponse sse_decode_ffi_auth_finish_response(
      SseDeserializer deserializer);

  @protected
  FfiAuthFinishResult sse_decode_ffi_auth_finish_result(
      SseDeserializer deserializer);

  @protected
  FfiAuthSessionResponse sse_decode_ffi_auth_session_response(
      SseDeserializer deserializer);

  @protected
  FfiAuthStartResponse sse_decode_ffi_auth_start_response(
      SseDeserializer deserializer);

  @protected
  FfiAuthStartResult sse_decode_ffi_auth_start_result(
      SseDeserializer deserializer);

  @protected
  FfiClientCapabilities sse_decode_ffi_client_capabilities(
      SseDeserializer deserializer);

  @protected
  FfiCourseResourceDetail sse_decode_ffi_course_resource_detail(
      SseDeserializer deserializer);

  @protected
  FfiCourseResourceDetailResponse
      sse_decode_ffi_course_resource_detail_response(
          SseDeserializer deserializer);

  @protected
  FfiCourseResourceSummary sse_decode_ffi_course_resource_summary(
      SseDeserializer deserializer);

  @protected
  FfiCourseResourcesResponse sse_decode_ffi_course_resources_response(
      SseDeserializer deserializer);

  @protected
  FfiCourseResponse sse_decode_ffi_course_response(
      SseDeserializer deserializer);

  @protected
  FfiCourseSite sse_decode_ffi_course_site(SseDeserializer deserializer);

  @protected
  FfiDownloadTaskStartResponse sse_decode_ffi_download_task_start_response(
      SseDeserializer deserializer);

  @protected
  FfiDownloadTaskState sse_decode_ffi_download_task_state(
      SseDeserializer deserializer);

  @protected
  FfiDownloadTaskStatus sse_decode_ffi_download_task_status(
      SseDeserializer deserializer);

  @protected
  FfiGoingSite sse_decode_ffi_going_site(SseDeserializer deserializer);

  @protected
  FfiLoginFlow sse_decode_ffi_login_flow(SseDeserializer deserializer);

  @protected
  FfiLogoutResponse sse_decode_ffi_logout_response(
      SseDeserializer deserializer);

  @protected
  FfiRoleInfo sse_decode_ffi_role_info(SseDeserializer deserializer);

  @protected
  FfiRoleName sse_decode_ffi_role_name(SseDeserializer deserializer);

  @protected
  FfiSessionUser sse_decode_ffi_session_user(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FfiAssignmentResource> sse_decode_list_ffi_assignment_resource(
      SseDeserializer deserializer);

  @protected
  List<FfiAssignmentSummary> sse_decode_list_ffi_assignment_summary(
      SseDeserializer deserializer);

  @protected
  List<FfiCourseResourceDetail> sse_decode_list_ffi_course_resource_detail(
      SseDeserializer deserializer);

  @protected
  List<FfiCourseResourceSummary> sse_decode_list_ffi_course_resource_summary(
      SseDeserializer deserializer);

  @protected
  List<FfiCourseSite> sse_decode_list_ffi_course_site(
      SseDeserializer deserializer);

  @protected
  List<FfiGoingSite> sse_decode_list_ffi_going_site(
      SseDeserializer deserializer);

  @protected
  List<FfiRoleInfo> sse_decode_list_ffi_role_info(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FfiRoleName? sse_decode_opt_box_autoadd_ffi_role_name(
      SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_auth_finish_request(
      FfiAuthFinishRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_login_flow(
      FfiLoginFlow self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_role_name(
      FfiRoleName self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_assignment_detail_response(
      FfiAssignmentDetailResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_assignment_list_response(
      FfiAssignmentListResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_assignment_resource(
      FfiAssignmentResource self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_assignment_status(
      FfiAssignmentStatus self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_assignment_submit_response(
      FfiAssignmentSubmitResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_assignment_summary(
      FfiAssignmentSummary self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_assignment_upload_response(
      FfiAssignmentUploadResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_attendance_qr_payload(
      FfiAttendanceQrPayload self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_error(FfiAuthError self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_error_code(
      FfiAuthErrorCode self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_finish_request(
      FfiAuthFinishRequest self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_finish_response(
      FfiAuthFinishResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_finish_result(
      FfiAuthFinishResult self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_session_response(
      FfiAuthSessionResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_start_response(
      FfiAuthStartResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_start_result(
      FfiAuthStartResult self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_client_capabilities(
      FfiClientCapabilities self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_course_resource_detail(
      FfiCourseResourceDetail self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_course_resource_detail_response(
      FfiCourseResourceDetailResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_course_resource_summary(
      FfiCourseResourceSummary self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_course_resources_response(
      FfiCourseResourcesResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_course_response(
      FfiCourseResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_course_site(FfiCourseSite self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_download_task_start_response(
      FfiDownloadTaskStartResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_download_task_state(
      FfiDownloadTaskState self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_download_task_status(
      FfiDownloadTaskStatus self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_going_site(FfiGoingSite self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_login_flow(FfiLoginFlow self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_logout_response(
      FfiLogoutResponse self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_role_info(FfiRoleInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_role_name(FfiRoleName self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_session_user(
      FfiSessionUser self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_assignment_resource(
      List<FfiAssignmentResource> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_assignment_summary(
      List<FfiAssignmentSummary> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_course_resource_detail(
      List<FfiCourseResourceDetail> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_course_resource_summary(
      List<FfiCourseResourceSummary> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_course_site(
      List<FfiCourseSite> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_going_site(
      List<FfiGoingSite> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_role_info(
      List<FfiRoleInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ffi_role_name(
      FfiRoleName? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
