// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -982138870;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'open_cloud_ffi',
        ioDirectory: '../target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<FfiAuthFinishResponse> crateApiAuthFinish({
    required FfiAuthFinishRequest request,
    required FfiLoginFlow flow,
  });

  Future<FfiAuthStartResponse> crateApiAuthStart({required String username});

  Future<FfiCourseResponse> crateApiCourses({
    required String sessionPayload,
    required bool withGoing,
  });

  Future<FfiLogoutResponse> crateApiLogout();

  Future<FfiAuthSessionResponse> crateApiSessionSummary({
    required String sessionPayload,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<FfiAuthFinishResponse> crateApiAuthFinish({
    required FfiAuthFinishRequest request,
    required FfiLoginFlow flow,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ffi_auth_finish_request(request, serializer);
          sse_encode_box_autoadd_ffi_login_flow(flow, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_auth_finish_response,
          decodeErrorData: sse_decode_ffi_auth_error,
        ),
        constMeta: kCrateApiAuthFinishConstMeta,
        argValues: [request, flow],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthFinishConstMeta => const TaskConstMeta(
    debugName: "auth_finish",
    argNames: ["request", "flow"],
  );

  @override
  Future<FfiAuthStartResponse> crateApiAuthStart({required String username}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_auth_start_response,
          decodeErrorData: sse_decode_ffi_auth_error,
        ),
        constMeta: kCrateApiAuthStartConstMeta,
        argValues: [username],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthStartConstMeta =>
      const TaskConstMeta(debugName: "auth_start", argNames: ["username"]);

  @override
  Future<FfiCourseResponse> crateApiCourses({
    required String sessionPayload,
    required bool withGoing,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionPayload, serializer);
          sse_encode_bool(withGoing, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_course_response,
          decodeErrorData: sse_decode_ffi_auth_error,
        ),
        constMeta: kCrateApiCoursesConstMeta,
        argValues: [sessionPayload, withGoing],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoursesConstMeta => const TaskConstMeta(
    debugName: "courses",
    argNames: ["sessionPayload", "withGoing"],
  );

  @override
  Future<FfiLogoutResponse> crateApiLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_logout_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: []);

  @override
  Future<FfiAuthSessionResponse> crateApiSessionSummary({
    required String sessionPayload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionPayload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_auth_session_response,
          decodeErrorData: sse_decode_ffi_auth_error,
        ),
        constMeta: kCrateApiSessionSummaryConstMeta,
        argValues: [sessionPayload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSummaryConstMeta => const TaskConstMeta(
    debugName: "session_summary",
    argNames: ["sessionPayload"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FfiAuthFinishRequest dco_decode_box_autoadd_ffi_auth_finish_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_auth_finish_request(raw);
  }

  @protected
  FfiLoginFlow dco_decode_box_autoadd_ffi_login_flow(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_login_flow(raw);
  }

  @protected
  FfiRoleName dco_decode_box_autoadd_ffi_role_name(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_role_name(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  FfiAuthError dco_decode_ffi_auth_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiAuthError(
      code: dco_decode_ffi_auth_error_code(arr[0]),
      message: dco_decode_String(arr[1]),
      retryAfterSeconds: dco_decode_opt_box_autoadd_u_64(arr[2]),
    );
  }

  @protected
  FfiAuthErrorCode dco_decode_ffi_auth_error_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FfiAuthErrorCode.values[raw as int];
  }

  @protected
  FfiAuthFinishRequest dco_decode_ffi_auth_finish_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FfiAuthFinishRequest(
      captcha: dco_decode_opt_String(arr[0]),
      flowId: dco_decode_String(arr[1]),
      password: dco_decode_String(arr[2]),
      role: dco_decode_opt_box_autoadd_ffi_role_name(arr[3]),
      username: dco_decode_String(arr[4]),
    );
  }

  @protected
  FfiAuthFinishResponse dco_decode_ffi_auth_finish_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiAuthFinishResponse(
      auth: dco_decode_ffi_auth_finish_result(arr[0]),
      sessionPayload: dco_decode_String(arr[1]),
    );
  }

  @protected
  FfiAuthFinishResult dco_decode_ffi_auth_finish_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiAuthFinishResult(
      roles: dco_decode_list_ffi_role_info(arr[0]),
      selectedRole: dco_decode_ffi_role_name(arr[1]),
      user: dco_decode_ffi_session_user(arr[2]),
    );
  }

  @protected
  FfiAuthSessionResponse dco_decode_ffi_auth_session_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiAuthSessionResponse(
      selectedRole: dco_decode_ffi_role_name(arr[0]),
      user: dco_decode_ffi_session_user(arr[1]),
    );
  }

  @protected
  FfiAuthStartResponse dco_decode_ffi_auth_start_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiAuthStartResponse(
      auth: dco_decode_ffi_auth_start_result(arr[0]),
      flow: dco_decode_ffi_login_flow(arr[1]),
    );
  }

  @protected
  FfiAuthStartResult dco_decode_ffi_auth_start_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiAuthStartResult(
      captchaImage: dco_decode_opt_String(arr[0]),
      flowId: dco_decode_String(arr[1]),
      requiresCaptcha: dco_decode_bool(arr[2]),
    );
  }

  @protected
  FfiCourseResponse dco_decode_ffi_course_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiCourseResponse(
      records: dco_decode_list_ffi_course_site(arr[0]),
      goingSites: dco_decode_list_ffi_going_site(arr[1]),
      updatedSessionPayload: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  FfiCourseSite dco_decode_ffi_course_site(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiCourseSite(
      id: dco_decode_String(arr[0]),
      siteName: dco_decode_String(arr[1]),
    );
  }

  @protected
  FfiGoingSite dco_decode_ffi_going_site(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiGoingSite(
      groupId: dco_decode_String(arr[0]),
      siteId: dco_decode_String(arr[1]),
    );
  }

  @protected
  FfiLoginFlow dco_decode_ffi_login_flow(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FfiLoginFlow(
      captchaId: dco_decode_opt_String(arr[0]),
      captchaImage: dco_decode_opt_String(arr[1]),
      cookie: dco_decode_String(arr[2]),
      createdAtMs: dco_decode_u_64(arr[3]),
      execution: dco_decode_String(arr[4]),
      username: dco_decode_String(arr[5]),
    );
  }

  @protected
  FfiLogoutResponse dco_decode_ffi_logout_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FfiLogoutResponse(clearSession: dco_decode_bool(arr[0]));
  }

  @protected
  FfiRoleInfo dco_decode_ffi_role_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FfiRoleInfo(
      domainId: dco_decode_String(arr[0]),
      domainName: dco_decode_String(arr[1]),
      id: dco_decode_String(arr[2]),
      roleAliase: dco_decode_String(arr[3]),
      roleId: dco_decode_String(arr[4]),
      roleName: dco_decode_ffi_role_name(arr[5]),
    );
  }

  @protected
  FfiRoleName dco_decode_ffi_role_name(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FfiRoleName.values[raw as int];
  }

  @protected
  FfiSessionUser dco_decode_ffi_session_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiSessionUser(
      account: dco_decode_String(arr[0]),
      realName: dco_decode_String(arr[1]),
      userId: dco_decode_String(arr[2]),
      userName: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<FfiCourseSite> dco_decode_list_ffi_course_site(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_course_site).toList();
  }

  @protected
  List<FfiGoingSite> dco_decode_list_ffi_going_site(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_going_site).toList();
  }

  @protected
  List<FfiRoleInfo> dco_decode_list_ffi_role_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_role_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FfiRoleName? dco_decode_opt_box_autoadd_ffi_role_name(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ffi_role_name(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FfiAuthFinishRequest sse_decode_box_autoadd_ffi_auth_finish_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_auth_finish_request(deserializer));
  }

  @protected
  FfiLoginFlow sse_decode_box_autoadd_ffi_login_flow(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_login_flow(deserializer));
  }

  @protected
  FfiRoleName sse_decode_box_autoadd_ffi_role_name(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_role_name(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  FfiAuthError sse_decode_ffi_auth_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_ffi_auth_error_code(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_retryAfterSeconds = sse_decode_opt_box_autoadd_u_64(deserializer);
    return FfiAuthError(
      code: var_code,
      message: var_message,
      retryAfterSeconds: var_retryAfterSeconds,
    );
  }

  @protected
  FfiAuthErrorCode sse_decode_ffi_auth_error_code(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FfiAuthErrorCode.values[inner];
  }

  @protected
  FfiAuthFinishRequest sse_decode_ffi_auth_finish_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_captcha = sse_decode_opt_String(deserializer);
    var var_flowId = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_role = sse_decode_opt_box_autoadd_ffi_role_name(deserializer);
    var var_username = sse_decode_String(deserializer);
    return FfiAuthFinishRequest(
      captcha: var_captcha,
      flowId: var_flowId,
      password: var_password,
      role: var_role,
      username: var_username,
    );
  }

  @protected
  FfiAuthFinishResponse sse_decode_ffi_auth_finish_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_auth = sse_decode_ffi_auth_finish_result(deserializer);
    var var_sessionPayload = sse_decode_String(deserializer);
    return FfiAuthFinishResponse(
      auth: var_auth,
      sessionPayload: var_sessionPayload,
    );
  }

  @protected
  FfiAuthFinishResult sse_decode_ffi_auth_finish_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roles = sse_decode_list_ffi_role_info(deserializer);
    var var_selectedRole = sse_decode_ffi_role_name(deserializer);
    var var_user = sse_decode_ffi_session_user(deserializer);
    return FfiAuthFinishResult(
      roles: var_roles,
      selectedRole: var_selectedRole,
      user: var_user,
    );
  }

  @protected
  FfiAuthSessionResponse sse_decode_ffi_auth_session_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_selectedRole = sse_decode_ffi_role_name(deserializer);
    var var_user = sse_decode_ffi_session_user(deserializer);
    return FfiAuthSessionResponse(
      selectedRole: var_selectedRole,
      user: var_user,
    );
  }

  @protected
  FfiAuthStartResponse sse_decode_ffi_auth_start_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_auth = sse_decode_ffi_auth_start_result(deserializer);
    var var_flow = sse_decode_ffi_login_flow(deserializer);
    return FfiAuthStartResponse(auth: var_auth, flow: var_flow);
  }

  @protected
  FfiAuthStartResult sse_decode_ffi_auth_start_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_captchaImage = sse_decode_opt_String(deserializer);
    var var_flowId = sse_decode_String(deserializer);
    var var_requiresCaptcha = sse_decode_bool(deserializer);
    return FfiAuthStartResult(
      captchaImage: var_captchaImage,
      flowId: var_flowId,
      requiresCaptcha: var_requiresCaptcha,
    );
  }

  @protected
  FfiCourseResponse sse_decode_ffi_course_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_records = sse_decode_list_ffi_course_site(deserializer);
    var var_goingSites = sse_decode_list_ffi_going_site(deserializer);
    var var_updatedSessionPayload = sse_decode_opt_String(deserializer);
    return FfiCourseResponse(
      records: var_records,
      goingSites: var_goingSites,
      updatedSessionPayload: var_updatedSessionPayload,
    );
  }

  @protected
  FfiCourseSite sse_decode_ffi_course_site(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_siteName = sse_decode_String(deserializer);
    return FfiCourseSite(id: var_id, siteName: var_siteName);
  }

  @protected
  FfiGoingSite sse_decode_ffi_going_site(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_groupId = sse_decode_String(deserializer);
    var var_siteId = sse_decode_String(deserializer);
    return FfiGoingSite(groupId: var_groupId, siteId: var_siteId);
  }

  @protected
  FfiLoginFlow sse_decode_ffi_login_flow(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_captchaId = sse_decode_opt_String(deserializer);
    var var_captchaImage = sse_decode_opt_String(deserializer);
    var var_cookie = sse_decode_String(deserializer);
    var var_createdAtMs = sse_decode_u_64(deserializer);
    var var_execution = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    return FfiLoginFlow(
      captchaId: var_captchaId,
      captchaImage: var_captchaImage,
      cookie: var_cookie,
      createdAtMs: var_createdAtMs,
      execution: var_execution,
      username: var_username,
    );
  }

  @protected
  FfiLogoutResponse sse_decode_ffi_logout_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_clearSession = sse_decode_bool(deserializer);
    return FfiLogoutResponse(clearSession: var_clearSession);
  }

  @protected
  FfiRoleInfo sse_decode_ffi_role_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_domainId = sse_decode_String(deserializer);
    var var_domainName = sse_decode_String(deserializer);
    var var_id = sse_decode_String(deserializer);
    var var_roleAliase = sse_decode_String(deserializer);
    var var_roleId = sse_decode_String(deserializer);
    var var_roleName = sse_decode_ffi_role_name(deserializer);
    return FfiRoleInfo(
      domainId: var_domainId,
      domainName: var_domainName,
      id: var_id,
      roleAliase: var_roleAliase,
      roleId: var_roleId,
      roleName: var_roleName,
    );
  }

  @protected
  FfiRoleName sse_decode_ffi_role_name(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FfiRoleName.values[inner];
  }

  @protected
  FfiSessionUser sse_decode_ffi_session_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_account = sse_decode_String(deserializer);
    var var_realName = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_userName = sse_decode_String(deserializer);
    return FfiSessionUser(
      account: var_account,
      realName: var_realName,
      userId: var_userId,
      userName: var_userName,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<FfiCourseSite> sse_decode_list_ffi_course_site(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiCourseSite>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_course_site(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiGoingSite> sse_decode_list_ffi_going_site(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiGoingSite>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_going_site(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiRoleInfo> sse_decode_list_ffi_role_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiRoleInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_role_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FfiRoleName? sse_decode_opt_box_autoadd_ffi_role_name(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ffi_role_name(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ffi_auth_finish_request(
    FfiAuthFinishRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_auth_finish_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_login_flow(
    FfiLoginFlow self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_login_flow(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_role_name(
    FfiRoleName self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_role_name(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_ffi_auth_error(FfiAuthError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_auth_error_code(self.code, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_box_autoadd_u_64(self.retryAfterSeconds, serializer);
  }

  @protected
  void sse_encode_ffi_auth_error_code(
    FfiAuthErrorCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ffi_auth_finish_request(
    FfiAuthFinishRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.captcha, serializer);
    sse_encode_String(self.flowId, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_opt_box_autoadd_ffi_role_name(self.role, serializer);
    sse_encode_String(self.username, serializer);
  }

  @protected
  void sse_encode_ffi_auth_finish_response(
    FfiAuthFinishResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_auth_finish_result(self.auth, serializer);
    sse_encode_String(self.sessionPayload, serializer);
  }

  @protected
  void sse_encode_ffi_auth_finish_result(
    FfiAuthFinishResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_ffi_role_info(self.roles, serializer);
    sse_encode_ffi_role_name(self.selectedRole, serializer);
    sse_encode_ffi_session_user(self.user, serializer);
  }

  @protected
  void sse_encode_ffi_auth_session_response(
    FfiAuthSessionResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_role_name(self.selectedRole, serializer);
    sse_encode_ffi_session_user(self.user, serializer);
  }

  @protected
  void sse_encode_ffi_auth_start_response(
    FfiAuthStartResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_auth_start_result(self.auth, serializer);
    sse_encode_ffi_login_flow(self.flow, serializer);
  }

  @protected
  void sse_encode_ffi_auth_start_result(
    FfiAuthStartResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.captchaImage, serializer);
    sse_encode_String(self.flowId, serializer);
    sse_encode_bool(self.requiresCaptcha, serializer);
  }

  @protected
  void sse_encode_ffi_course_response(
    FfiCourseResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_ffi_course_site(self.records, serializer);
    sse_encode_list_ffi_going_site(self.goingSites, serializer);
    sse_encode_opt_String(self.updatedSessionPayload, serializer);
  }

  @protected
  void sse_encode_ffi_course_site(
    FfiCourseSite self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.siteName, serializer);
  }

  @protected
  void sse_encode_ffi_going_site(FfiGoingSite self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.groupId, serializer);
    sse_encode_String(self.siteId, serializer);
  }

  @protected
  void sse_encode_ffi_login_flow(FfiLoginFlow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.captchaId, serializer);
    sse_encode_opt_String(self.captchaImage, serializer);
    sse_encode_String(self.cookie, serializer);
    sse_encode_u_64(self.createdAtMs, serializer);
    sse_encode_String(self.execution, serializer);
    sse_encode_String(self.username, serializer);
  }

  @protected
  void sse_encode_ffi_logout_response(
    FfiLogoutResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.clearSession, serializer);
  }

  @protected
  void sse_encode_ffi_role_info(FfiRoleInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.domainId, serializer);
    sse_encode_String(self.domainName, serializer);
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.roleAliase, serializer);
    sse_encode_String(self.roleId, serializer);
    sse_encode_ffi_role_name(self.roleName, serializer);
  }

  @protected
  void sse_encode_ffi_role_name(FfiRoleName self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ffi_session_user(
    FfiSessionUser self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.account, serializer);
    sse_encode_String(self.realName, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.userName, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_ffi_course_site(
    List<FfiCourseSite> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_course_site(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_going_site(
    List<FfiGoingSite> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_going_site(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_role_info(
    List<FfiRoleInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_role_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ffi_role_name(
    FfiRoleName? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ffi_role_name(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
