// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FfiAuthFinishRequest dco_decode_box_autoadd_ffi_auth_finish_request(
    dynamic raw,
  );

  @protected
  FfiLoginFlow dco_decode_box_autoadd_ffi_login_flow(dynamic raw);

  @protected
  FfiRoleName dco_decode_box_autoadd_ffi_role_name(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  FfiAuthError dco_decode_ffi_auth_error(dynamic raw);

  @protected
  FfiAuthErrorCode dco_decode_ffi_auth_error_code(dynamic raw);

  @protected
  FfiAuthFinishRequest dco_decode_ffi_auth_finish_request(dynamic raw);

  @protected
  FfiAuthFinishResponse dco_decode_ffi_auth_finish_response(dynamic raw);

  @protected
  FfiAuthFinishResult dco_decode_ffi_auth_finish_result(dynamic raw);

  @protected
  FfiAuthSessionResponse dco_decode_ffi_auth_session_response(dynamic raw);

  @protected
  FfiAuthStartResponse dco_decode_ffi_auth_start_response(dynamic raw);

  @protected
  FfiAuthStartResult dco_decode_ffi_auth_start_result(dynamic raw);

  @protected
  FfiCourseResponse dco_decode_ffi_course_response(dynamic raw);

  @protected
  FfiCourseSite dco_decode_ffi_course_site(dynamic raw);

  @protected
  FfiGoingSite dco_decode_ffi_going_site(dynamic raw);

  @protected
  FfiLoginFlow dco_decode_ffi_login_flow(dynamic raw);

  @protected
  FfiLogoutResponse dco_decode_ffi_logout_response(dynamic raw);

  @protected
  FfiRoleInfo dco_decode_ffi_role_info(dynamic raw);

  @protected
  FfiRoleName dco_decode_ffi_role_name(dynamic raw);

  @protected
  FfiSessionUser dco_decode_ffi_session_user(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<FfiCourseSite> dco_decode_list_ffi_course_site(dynamic raw);

  @protected
  List<FfiGoingSite> dco_decode_list_ffi_going_site(dynamic raw);

  @protected
  List<FfiRoleInfo> dco_decode_list_ffi_role_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FfiRoleName? dco_decode_opt_box_autoadd_ffi_role_name(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FfiAuthFinishRequest sse_decode_box_autoadd_ffi_auth_finish_request(
    SseDeserializer deserializer,
  );

  @protected
  FfiLoginFlow sse_decode_box_autoadd_ffi_login_flow(
    SseDeserializer deserializer,
  );

  @protected
  FfiRoleName sse_decode_box_autoadd_ffi_role_name(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  FfiAuthError sse_decode_ffi_auth_error(SseDeserializer deserializer);

  @protected
  FfiAuthErrorCode sse_decode_ffi_auth_error_code(SseDeserializer deserializer);

  @protected
  FfiAuthFinishRequest sse_decode_ffi_auth_finish_request(
    SseDeserializer deserializer,
  );

  @protected
  FfiAuthFinishResponse sse_decode_ffi_auth_finish_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiAuthFinishResult sse_decode_ffi_auth_finish_result(
    SseDeserializer deserializer,
  );

  @protected
  FfiAuthSessionResponse sse_decode_ffi_auth_session_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiAuthStartResponse sse_decode_ffi_auth_start_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiAuthStartResult sse_decode_ffi_auth_start_result(
    SseDeserializer deserializer,
  );

  @protected
  FfiCourseResponse sse_decode_ffi_course_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiCourseSite sse_decode_ffi_course_site(SseDeserializer deserializer);

  @protected
  FfiGoingSite sse_decode_ffi_going_site(SseDeserializer deserializer);

  @protected
  FfiLoginFlow sse_decode_ffi_login_flow(SseDeserializer deserializer);

  @protected
  FfiLogoutResponse sse_decode_ffi_logout_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiRoleInfo sse_decode_ffi_role_info(SseDeserializer deserializer);

  @protected
  FfiRoleName sse_decode_ffi_role_name(SseDeserializer deserializer);

  @protected
  FfiSessionUser sse_decode_ffi_session_user(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<FfiCourseSite> sse_decode_list_ffi_course_site(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiGoingSite> sse_decode_list_ffi_going_site(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiRoleInfo> sse_decode_list_ffi_role_info(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FfiRoleName? sse_decode_opt_box_autoadd_ffi_role_name(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_auth_finish_request(
    FfiAuthFinishRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_login_flow(
    FfiLoginFlow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_role_name(
    FfiRoleName self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_error(FfiAuthError self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_error_code(
    FfiAuthErrorCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_auth_finish_request(
    FfiAuthFinishRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_auth_finish_response(
    FfiAuthFinishResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_auth_finish_result(
    FfiAuthFinishResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_auth_session_response(
    FfiAuthSessionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_auth_start_response(
    FfiAuthStartResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_auth_start_result(
    FfiAuthStartResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_course_response(
    FfiCourseResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_course_site(FfiCourseSite self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_going_site(FfiGoingSite self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_login_flow(FfiLoginFlow self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_logout_response(
    FfiLogoutResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_role_info(FfiRoleInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_role_name(FfiRoleName self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_session_user(
    FfiSessionUser self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_course_site(
    List<FfiCourseSite> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_going_site(
    List<FfiGoingSite> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_role_info(
    List<FfiRoleInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ffi_role_name(
    FfiRoleName? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
