[package]
name = "open-ucloud-cli"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["open-ucloud-store/default"]
desktop-keyring = ["open-ucloud-store/desktop-keyring"]
linux-secret-service = ["open-ucloud-store/linux-secret-service"]
linux-secret-service-vendored = ["open-ucloud-store/linux-secret-service-vendored"]

[[bin]]
name = "open-ucloud"
path = "src/main.rs"

[lib]
name = "open_ucloud_cli"
path = "src/lib.rs"

[dependencies]
clap.workspace = true
open-ucloud-api = { path = "../api" }
open-ucloud-core = { path = "../core" }
open-ucloud-store = { path = "../store", default-features = false }
rpassword.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
async-trait.workspace = true
