// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -982138870;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__auth_finish_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "auth_finish",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::FfiAuthFinishRequest>::sse_decode(&mut deserializer);
            let api_flow = <crate::api::FfiLoginFlow>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::FfiAuthError>(
                    (move || async move {
                        let output_ok = crate::api::auth_finish(api_request, api_flow).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__auth_start_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "auth_start",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_username = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::FfiAuthError>(
                    (move || async move {
                        let output_ok = crate::api::auth_start(api_username).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__courses_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "courses",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_payload = <String>::sse_decode(&mut deserializer);
            let api_with_going = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::FfiAuthError>(
                    (move || async move {
                        let output_ok =
                            crate::api::courses(api_session_payload, api_with_going).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__logout_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "logout",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::logout())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__session_summary_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "session_summary",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_payload = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::FfiAuthError>((move || {
                    let output_ok = crate::api::session_summary(api_session_payload)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::FfiAuthError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <crate::api::FfiAuthErrorCode>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_retryAfterSeconds = <Option<u64>>::sse_decode(deserializer);
        return crate::api::FfiAuthError {
            code: var_code,
            message: var_message,
            retry_after_seconds: var_retryAfterSeconds,
        };
    }
}

impl SseDecode for crate::api::FfiAuthErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::FfiAuthErrorCode::CaptchaRequired,
            1 => crate::api::FfiAuthErrorCode::CaptchaInvalid,
            2 => crate::api::FfiAuthErrorCode::EmptyUpload,
            3 => crate::api::FfiAuthErrorCode::FileTooLarge,
            4 => crate::api::FfiAuthErrorCode::InvalidFileName,
            5 => crate::api::FfiAuthErrorCode::FileTypeNotAllowed,
            6 => crate::api::FfiAuthErrorCode::FlowExpired,
            7 => crate::api::FfiAuthErrorCode::InvalidCredentials,
            8 => crate::api::FfiAuthErrorCode::RoleNotFound,
            9 => crate::api::FfiAuthErrorCode::SecureStorageUnavailable,
            10 => crate::api::FfiAuthErrorCode::SessionExpired,
            11 => crate::api::FfiAuthErrorCode::UpstreamUnavailable,
            12 => crate::api::FfiAuthErrorCode::UnknownAuthError,
            _ => unreachable!("Invalid variant for FfiAuthErrorCode: {}", inner),
        };
    }
}

impl SseDecode for crate::api::FfiAuthFinishRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_captcha = <Option<String>>::sse_decode(deserializer);
        let mut var_flowId = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_role = <Option<crate::api::FfiRoleName>>::sse_decode(deserializer);
        let mut var_username = <String>::sse_decode(deserializer);
        return crate::api::FfiAuthFinishRequest {
            captcha: var_captcha,
            flow_id: var_flowId,
            password: var_password,
            role: var_role,
            username: var_username,
        };
    }
}

impl SseDecode for crate::api::FfiAuthFinishResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_auth = <crate::api::FfiAuthFinishResult>::sse_decode(deserializer);
        let mut var_sessionPayload = <String>::sse_decode(deserializer);
        return crate::api::FfiAuthFinishResponse {
            auth: var_auth,
            session_payload: var_sessionPayload,
        };
    }
}

impl SseDecode for crate::api::FfiAuthFinishResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_roles = <Vec<crate::api::FfiRoleInfo>>::sse_decode(deserializer);
        let mut var_selectedRole = <crate::api::FfiRoleName>::sse_decode(deserializer);
        let mut var_user = <crate::api::FfiSessionUser>::sse_decode(deserializer);
        return crate::api::FfiAuthFinishResult {
            roles: var_roles,
            selected_role: var_selectedRole,
            user: var_user,
        };
    }
}

impl SseDecode for crate::api::FfiAuthSessionResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_selectedRole = <crate::api::FfiRoleName>::sse_decode(deserializer);
        let mut var_user = <crate::api::FfiSessionUser>::sse_decode(deserializer);
        return crate::api::FfiAuthSessionResponse {
            selected_role: var_selectedRole,
            user: var_user,
        };
    }
}

impl SseDecode for crate::api::FfiAuthStartResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_auth = <crate::api::FfiAuthStartResult>::sse_decode(deserializer);
        let mut var_flow = <crate::api::FfiLoginFlow>::sse_decode(deserializer);
        return crate::api::FfiAuthStartResponse {
            auth: var_auth,
            flow: var_flow,
        };
    }
}

impl SseDecode for crate::api::FfiAuthStartResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_captchaImage = <Option<String>>::sse_decode(deserializer);
        let mut var_flowId = <String>::sse_decode(deserializer);
        let mut var_requiresCaptcha = <bool>::sse_decode(deserializer);
        return crate::api::FfiAuthStartResult {
            captcha_image: var_captchaImage,
            flow_id: var_flowId,
            requires_captcha: var_requiresCaptcha,
        };
    }
}

impl SseDecode for crate::api::FfiCourseResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_records = <Vec<crate::api::FfiCourseSite>>::sse_decode(deserializer);
        let mut var_goingSites = <Vec<crate::api::FfiGoingSite>>::sse_decode(deserializer);
        let mut var_updatedSessionPayload = <Option<String>>::sse_decode(deserializer);
        return crate::api::FfiCourseResponse {
            records: var_records,
            going_sites: var_goingSites,
            updated_session_payload: var_updatedSessionPayload,
        };
    }
}

impl SseDecode for crate::api::FfiCourseSite {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_siteName = <String>::sse_decode(deserializer);
        return crate::api::FfiCourseSite {
            id: var_id,
            site_name: var_siteName,
        };
    }
}

impl SseDecode for crate::api::FfiGoingSite {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_groupId = <String>::sse_decode(deserializer);
        let mut var_siteId = <String>::sse_decode(deserializer);
        return crate::api::FfiGoingSite {
            group_id: var_groupId,
            site_id: var_siteId,
        };
    }
}

impl SseDecode for crate::api::FfiLoginFlow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_captchaId = <Option<String>>::sse_decode(deserializer);
        let mut var_captchaImage = <Option<String>>::sse_decode(deserializer);
        let mut var_cookie = <String>::sse_decode(deserializer);
        let mut var_createdAtMs = <u64>::sse_decode(deserializer);
        let mut var_execution = <String>::sse_decode(deserializer);
        let mut var_username = <String>::sse_decode(deserializer);
        return crate::api::FfiLoginFlow {
            captcha_id: var_captchaId,
            captcha_image: var_captchaImage,
            cookie: var_cookie,
            created_at_ms: var_createdAtMs,
            execution: var_execution,
            username: var_username,
        };
    }
}

impl SseDecode for crate::api::FfiLogoutResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_clearSession = <bool>::sse_decode(deserializer);
        return crate::api::FfiLogoutResponse {
            clear_session: var_clearSession,
        };
    }
}

impl SseDecode for crate::api::FfiRoleInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_domainId = <String>::sse_decode(deserializer);
        let mut var_domainName = <String>::sse_decode(deserializer);
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_roleAliase = <String>::sse_decode(deserializer);
        let mut var_roleId = <String>::sse_decode(deserializer);
        let mut var_roleName = <crate::api::FfiRoleName>::sse_decode(deserializer);
        return crate::api::FfiRoleInfo {
            domain_id: var_domainId,
            domain_name: var_domainName,
            id: var_id,
            role_aliase: var_roleAliase,
            role_id: var_roleId,
            role_name: var_roleName,
        };
    }
}

impl SseDecode for crate::api::FfiRoleName {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::FfiRoleName::Student,
            1 => crate::api::FfiRoleName::Teacher,
            2 => crate::api::FfiRoleName::Assistant,
            _ => unreachable!("Invalid variant for FfiRoleName: {}", inner),
        };
    }
}

impl SseDecode for crate::api::FfiSessionUser {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_account = <String>::sse_decode(deserializer);
        let mut var_realName = <String>::sse_decode(deserializer);
        let mut var_userId = <String>::sse_decode(deserializer);
        let mut var_userName = <String>::sse_decode(deserializer);
        return crate::api::FfiSessionUser {
            account: var_account,
            real_name: var_realName,
            user_id: var_userId,
            user_name: var_userName,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::FfiCourseSite> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FfiCourseSite>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::FfiGoingSite> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FfiGoingSite>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::FfiRoleInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FfiRoleInfo>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::FfiRoleName> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::FfiRoleName>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__auth_finish_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__auth_start_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__courses_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__logout_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__session_summary_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiAuthError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.retry_after_seconds.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiAuthError {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiAuthError> for crate::api::FfiAuthError {
    fn into_into_dart(self) -> crate::api::FfiAuthError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiAuthErrorCode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::CaptchaRequired => 0.into_dart(),
            Self::CaptchaInvalid => 1.into_dart(),
            Self::EmptyUpload => 2.into_dart(),
            Self::FileTooLarge => 3.into_dart(),
            Self::InvalidFileName => 4.into_dart(),
            Self::FileTypeNotAllowed => 5.into_dart(),
            Self::FlowExpired => 6.into_dart(),
            Self::InvalidCredentials => 7.into_dart(),
            Self::RoleNotFound => 8.into_dart(),
            Self::SecureStorageUnavailable => 9.into_dart(),
            Self::SessionExpired => 10.into_dart(),
            Self::UpstreamUnavailable => 11.into_dart(),
            Self::UnknownAuthError => 12.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiAuthErrorCode {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiAuthErrorCode>
    for crate::api::FfiAuthErrorCode
{
    fn into_into_dart(self) -> crate::api::FfiAuthErrorCode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiAuthFinishRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.captcha.into_into_dart().into_dart(),
            self.flow_id.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.role.into_into_dart().into_dart(),
            self.username.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiAuthFinishRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiAuthFinishRequest>
    for crate::api::FfiAuthFinishRequest
{
    fn into_into_dart(self) -> crate::api::FfiAuthFinishRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiAuthFinishResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.auth.into_into_dart().into_dart(),
            self.session_payload.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiAuthFinishResponse
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiAuthFinishResponse>
    for crate::api::FfiAuthFinishResponse
{
    fn into_into_dart(self) -> crate::api::FfiAuthFinishResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiAuthFinishResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.roles.into_into_dart().into_dart(),
            self.selected_role.into_into_dart().into_dart(),
            self.user.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiAuthFinishResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiAuthFinishResult>
    for crate::api::FfiAuthFinishResult
{
    fn into_into_dart(self) -> crate::api::FfiAuthFinishResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiAuthSessionResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.selected_role.into_into_dart().into_dart(),
            self.user.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiAuthSessionResponse
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiAuthSessionResponse>
    for crate::api::FfiAuthSessionResponse
{
    fn into_into_dart(self) -> crate::api::FfiAuthSessionResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiAuthStartResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.auth.into_into_dart().into_dart(),
            self.flow.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiAuthStartResponse
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiAuthStartResponse>
    for crate::api::FfiAuthStartResponse
{
    fn into_into_dart(self) -> crate::api::FfiAuthStartResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiAuthStartResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.captcha_image.into_into_dart().into_dart(),
            self.flow_id.into_into_dart().into_dart(),
            self.requires_captcha.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiAuthStartResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiAuthStartResult>
    for crate::api::FfiAuthStartResult
{
    fn into_into_dart(self) -> crate::api::FfiAuthStartResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiCourseResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.records.into_into_dart().into_dart(),
            self.going_sites.into_into_dart().into_dart(),
            self.updated_session_payload.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiCourseResponse {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiCourseResponse>
    for crate::api::FfiCourseResponse
{
    fn into_into_dart(self) -> crate::api::FfiCourseResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiCourseSite {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.site_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiCourseSite {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiCourseSite> for crate::api::FfiCourseSite {
    fn into_into_dart(self) -> crate::api::FfiCourseSite {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiGoingSite {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.group_id.into_into_dart().into_dart(),
            self.site_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiGoingSite {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiGoingSite> for crate::api::FfiGoingSite {
    fn into_into_dart(self) -> crate::api::FfiGoingSite {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiLoginFlow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.captcha_id.into_into_dart().into_dart(),
            self.captcha_image.into_into_dart().into_dart(),
            self.cookie.into_into_dart().into_dart(),
            self.created_at_ms.into_into_dart().into_dart(),
            self.execution.into_into_dart().into_dart(),
            self.username.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiLoginFlow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiLoginFlow> for crate::api::FfiLoginFlow {
    fn into_into_dart(self) -> crate::api::FfiLoginFlow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiLogoutResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.clear_session.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiLogoutResponse {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiLogoutResponse>
    for crate::api::FfiLogoutResponse
{
    fn into_into_dart(self) -> crate::api::FfiLogoutResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiRoleInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.domain_id.into_into_dart().into_dart(),
            self.domain_name.into_into_dart().into_dart(),
            self.id.into_into_dart().into_dart(),
            self.role_aliase.into_into_dart().into_dart(),
            self.role_id.into_into_dart().into_dart(),
            self.role_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiRoleInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiRoleInfo> for crate::api::FfiRoleInfo {
    fn into_into_dart(self) -> crate::api::FfiRoleInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiRoleName {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Student => 0.into_dart(),
            Self::Teacher => 1.into_dart(),
            Self::Assistant => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiRoleName {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiRoleName> for crate::api::FfiRoleName {
    fn into_into_dart(self) -> crate::api::FfiRoleName {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiSessionUser {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.account.into_into_dart().into_dart(),
            self.real_name.into_into_dart().into_dart(),
            self.user_id.into_into_dart().into_dart(),
            self.user_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiSessionUser {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiSessionUser> for crate::api::FfiSessionUser {
    fn into_into_dart(self) -> crate::api::FfiSessionUser {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::FfiAuthError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::FfiAuthErrorCode>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.message, serializer);
        <Option<u64>>::sse_encode(self.retry_after_seconds, serializer);
    }
}

impl SseEncode for crate::api::FfiAuthErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::FfiAuthErrorCode::CaptchaRequired => 0,
                crate::api::FfiAuthErrorCode::CaptchaInvalid => 1,
                crate::api::FfiAuthErrorCode::EmptyUpload => 2,
                crate::api::FfiAuthErrorCode::FileTooLarge => 3,
                crate::api::FfiAuthErrorCode::InvalidFileName => 4,
                crate::api::FfiAuthErrorCode::FileTypeNotAllowed => 5,
                crate::api::FfiAuthErrorCode::FlowExpired => 6,
                crate::api::FfiAuthErrorCode::InvalidCredentials => 7,
                crate::api::FfiAuthErrorCode::RoleNotFound => 8,
                crate::api::FfiAuthErrorCode::SecureStorageUnavailable => 9,
                crate::api::FfiAuthErrorCode::SessionExpired => 10,
                crate::api::FfiAuthErrorCode::UpstreamUnavailable => 11,
                crate::api::FfiAuthErrorCode::UnknownAuthError => 12,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::FfiAuthFinishRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.captcha, serializer);
        <String>::sse_encode(self.flow_id, serializer);
        <String>::sse_encode(self.password, serializer);
        <Option<crate::api::FfiRoleName>>::sse_encode(self.role, serializer);
        <String>::sse_encode(self.username, serializer);
    }
}

impl SseEncode for crate::api::FfiAuthFinishResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::FfiAuthFinishResult>::sse_encode(self.auth, serializer);
        <String>::sse_encode(self.session_payload, serializer);
    }
}

impl SseEncode for crate::api::FfiAuthFinishResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::FfiRoleInfo>>::sse_encode(self.roles, serializer);
        <crate::api::FfiRoleName>::sse_encode(self.selected_role, serializer);
        <crate::api::FfiSessionUser>::sse_encode(self.user, serializer);
    }
}

impl SseEncode for crate::api::FfiAuthSessionResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::FfiRoleName>::sse_encode(self.selected_role, serializer);
        <crate::api::FfiSessionUser>::sse_encode(self.user, serializer);
    }
}

impl SseEncode for crate::api::FfiAuthStartResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::FfiAuthStartResult>::sse_encode(self.auth, serializer);
        <crate::api::FfiLoginFlow>::sse_encode(self.flow, serializer);
    }
}

impl SseEncode for crate::api::FfiAuthStartResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.captcha_image, serializer);
        <String>::sse_encode(self.flow_id, serializer);
        <bool>::sse_encode(self.requires_captcha, serializer);
    }
}

impl SseEncode for crate::api::FfiCourseResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::FfiCourseSite>>::sse_encode(self.records, serializer);
        <Vec<crate::api::FfiGoingSite>>::sse_encode(self.going_sites, serializer);
        <Option<String>>::sse_encode(self.updated_session_payload, serializer);
    }
}

impl SseEncode for crate::api::FfiCourseSite {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.site_name, serializer);
    }
}

impl SseEncode for crate::api::FfiGoingSite {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.group_id, serializer);
        <String>::sse_encode(self.site_id, serializer);
    }
}

impl SseEncode for crate::api::FfiLoginFlow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.captcha_id, serializer);
        <Option<String>>::sse_encode(self.captcha_image, serializer);
        <String>::sse_encode(self.cookie, serializer);
        <u64>::sse_encode(self.created_at_ms, serializer);
        <String>::sse_encode(self.execution, serializer);
        <String>::sse_encode(self.username, serializer);
    }
}

impl SseEncode for crate::api::FfiLogoutResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.clear_session, serializer);
    }
}

impl SseEncode for crate::api::FfiRoleInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.domain_id, serializer);
        <String>::sse_encode(self.domain_name, serializer);
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.role_aliase, serializer);
        <String>::sse_encode(self.role_id, serializer);
        <crate::api::FfiRoleName>::sse_encode(self.role_name, serializer);
    }
}

impl SseEncode for crate::api::FfiRoleName {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::FfiRoleName::Student => 0,
                crate::api::FfiRoleName::Teacher => 1,
                crate::api::FfiRoleName::Assistant => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::FfiSessionUser {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.account, serializer);
        <String>::sse_encode(self.real_name, serializer);
        <String>::sse_encode(self.user_id, serializer);
        <String>::sse_encode(self.user_name, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::FfiCourseSite> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FfiCourseSite>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::FfiGoingSite> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FfiGoingSite>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::FfiRoleInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FfiRoleInfo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::FfiRoleName> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::FfiRoleName>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
